language: go

go:
  - tip

sudo: required

install:
        sudo apt-get install libpcap-dev
        go get github.com/google/gopacket
        go get github.com/go-ini/ini

script:
  - go test -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
  
